version: '3'

services:
  db:
    image: mongo:5.0.0
    restart: always
    container_name: nest-pokemon-database
    ports:
      - 27018:27017
    environment:
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
